AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  RunRailsCops: true

#
# Line is too long.
Metrics/LineLength:
  Max: 120 # Default: 80
#  Exclude:
#    - 'spec/models/*_spec.rb'

#
# Method has too many lines.
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Exclude:
    - 'db/migrate/**/*'

#
# Assignment Branch Condition size for change is too high.
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'
